export type SmartphoneOs = 'iOS' | 'Android'

export type SmartphoneSpec = {
  id: string
  name: string
  maker: string
  os: SmartphoneOs
  generation: string
  releaseYear: number
  storageGb: number
  priceYen: number
  priceNote: string
  displayInch: number
  refreshRateHz: number
  weightG: number
  batteryLabel: string
  batteryScore: number
  chip: string
  ramGb?: number
  mainCameraMp: number
  ultrawideMp?: number
  telephotoMp?: number
  opticalZoomLabel: string
  cameraScore: number
  performanceScore: number
  aiScore: number
  videoScore: number
  updateYears: number
  waterResistance: string
  charging: string
  sourceUrl: string
  checkedDate: string
  strengths: string[]
  cautions: string[]
  bestFor: string
}

export const SMARTPHONE_DATA_NOTE =
  '価格は2026年5月8日時点で確認したメーカー直販・公式発表価格を中心にした税込目安です。キャリア施策、下取り、ポイント、在庫色で変わるため、購入前に公式販売ページを確認してください。'

export const SMARTPHONE_DATA: SmartphoneSpec[] = [
  {
    id: 'iphone-17e-256',
    name: 'iPhone 17e',
    maker: 'Apple',
    os: 'iOS',
    generation: 'iPhone 17',
    releaseYear: 2026,
    storageGb: 256,
    priceYen: 99800,
    priceNote: 'Apple直販 256GB',
    displayInch: 6.1,
    refreshRateHz: 60,
    weightG: 169,
    batteryLabel: 'ビデオ再生 最大26時間',
    batteryScore: 78,
    chip: 'A19',
    mainCameraMp: 48,
    opticalZoomLabel: '2倍相当',
    cameraScore: 72,
    performanceScore: 86,
    aiScore: 82,
    videoScore: 76,
    updateYears: 5,
    waterResistance: 'IP68',
    charging: 'USB-C / MagSafe 15W',
    sourceUrl: 'https://www.apple.com/jp/iphone-17e/specs/',
    checkedDate: '2026-05-08',
    strengths: ['256GB開始で価格を抑えやすい', '軽めの本体', 'iOSとApple Intelligenceを安く使える'],
    cautions: ['高リフレッシュレート非対応', '超広角や本格望遠はない'],
    bestFor: '長く使えるiPhoneを価格重視で選びたい人',
  },
  {
    id: 'iphone-17-256',
    name: 'iPhone 17',
    maker: 'Apple',
    os: 'iOS',
    generation: 'iPhone 17',
    releaseYear: 2025,
    storageGb: 256,
    priceYen: 129800,
    priceNote: 'Apple直販 256GB',
    displayInch: 6.3,
    refreshRateHz: 120,
    weightG: 177,
    batteryLabel: 'ビデオ再生 最大30時間',
    batteryScore: 84,
    chip: 'A19',
    mainCameraMp: 48,
    ultrawideMp: 48,
    opticalZoomLabel: '2倍相当',
    cameraScore: 82,
    performanceScore: 88,
    aiScore: 84,
    videoScore: 84,
    updateYears: 5,
    waterResistance: 'IP68',
    charging: 'USB-C / MagSafe',
    sourceUrl: 'https://www.apple.com/jp/iphone-17/specs/',
    checkedDate: '2026-05-08',
    strengths: ['120Hz対応で普段使いが滑らか', '標準モデルとして軽さと性能のバランスが良い', '超広角も使える'],
    cautions: ['本格的な望遠撮影はProが有利', 'Androidの自由度を求める人には不向き'],
    bestFor: 'iPhoneで迷ったときの標準解',
  },
  {
    id: 'iphone-17-pro-256',
    name: 'iPhone 17 Pro',
    maker: 'Apple',
    os: 'iOS',
    generation: 'iPhone 17 Pro',
    releaseYear: 2025,
    storageGb: 256,
    priceYen: 194800,
    priceNote: 'Apple直販 256GB',
    displayInch: 6.3,
    refreshRateHz: 120,
    weightG: 206,
    batteryLabel: 'ビデオ再生 最大33時間',
    batteryScore: 90,
    chip: 'A19 Pro',
    mainCameraMp: 48,
    ultrawideMp: 48,
    telephotoMp: 48,
    opticalZoomLabel: '最大8倍相当',
    cameraScore: 96,
    performanceScore: 96,
    aiScore: 90,
    videoScore: 98,
    updateYears: 5,
    waterResistance: 'IP68',
    charging: 'USB-C USB 3 / MagSafe 25W',
    sourceUrl: 'https://www.apple.com/jp/iphone-17-pro/specs/',
    checkedDate: '2026-05-08',
    strengths: ['写真・動画が強い', 'ProRes RAWやUSB 3に対応', '高性能チップでゲームや編集にも強い'],
    cautions: ['価格が高い', '206gで軽量重視には向きにくい'],
    bestFor: '動画撮影、SNS制作、長く使うハイエンドiPhoneが欲しい人',
  },
  {
    id: 'pixel-10-128',
    name: 'Google Pixel 10',
    maker: 'Google',
    os: 'Android',
    generation: 'Pixel 10',
    releaseYear: 2025,
    storageGb: 128,
    priceYen: 128900,
    priceNote: 'Googleストア 128GB目安',
    displayInch: 6.3,
    refreshRateHz: 120,
    weightG: 198,
    batteryLabel: '30時間以上',
    batteryScore: 86,
    chip: 'Google Tensor G5',
    ramGb: 12,
    mainCameraMp: 48,
    ultrawideMp: 13,
    telephotoMp: 10.8,
    opticalZoomLabel: '20倍ズーム',
    cameraScore: 86,
    performanceScore: 84,
    aiScore: 94,
    videoScore: 82,
    updateYears: 7,
    waterResistance: 'IP68',
    charging: 'USB-C / Pixelsnap Qi2',
    sourceUrl: 'https://store.google.com/jp/product/pixel_10?hl=ja',
    checkedDate: '2026-05-08',
    strengths: ['AI機能と通話補助が強い', '7年アップデート', '標準モデルでも望遠あり'],
    cautions: ['最小ストレージは128GB', 'ゲーム性能最優先なら別候補も検討'],
    bestFor: 'AI機能、写真補正、長期アップデートを重視する人',
  },
  {
    id: 'pixel-10-pro-128',
    name: 'Google Pixel 10 Pro',
    maker: 'Google',
    os: 'Android',
    generation: 'Pixel 10 Pro',
    releaseYear: 2025,
    storageGb: 128,
    priceYen: 174900,
    priceNote: 'Googleストア 128GB',
    displayInch: 6.3,
    refreshRateHz: 120,
    weightG: 207,
    batteryLabel: '30時間以上',
    batteryScore: 88,
    chip: 'Google Tensor G5',
    ramGb: 16,
    mainCameraMp: 50,
    ultrawideMp: 48,
    telephotoMp: 48,
    opticalZoomLabel: '100倍ズーム',
    cameraScore: 95,
    performanceScore: 88,
    aiScore: 98,
    videoScore: 92,
    updateYears: 7,
    waterResistance: 'IP68',
    charging: 'USB-C / Pixelsnap Qi2',
    sourceUrl: 'https://store.google.com/jp/product/pixel_10_pro?hl=ja',
    checkedDate: '2026-05-08',
    strengths: ['AI処理と写真補正が非常に強い', '16GB RAM', 'Pro級カメラを比較的コンパクトに使える'],
    cautions: ['128GB開始なので保存容量に注意', '重量は200g超え'],
    bestFor: '写真、AI、Androidの長期運用を重視する人',
  },
  {
    id: 'galaxy-s26-256',
    name: 'Galaxy S26',
    maker: 'Samsung',
    os: 'Android',
    generation: 'Galaxy S26',
    releaseYear: 2026,
    storageGb: 256,
    priceYen: 136400,
    priceNote: 'Samsungオンラインショップ 256GB',
    displayInch: 6.3,
    refreshRateHz: 120,
    weightG: 167,
    batteryLabel: '4,300mAh',
    batteryScore: 82,
    chip: 'Snapdragon / Exynos世代',
    ramGb: 12,
    mainCameraMp: 50,
    ultrawideMp: 12,
    telephotoMp: 10,
    opticalZoomLabel: '望遠搭載',
    cameraScore: 84,
    performanceScore: 90,
    aiScore: 92,
    videoScore: 84,
    updateYears: 7,
    waterResistance: 'IP68',
    charging: 'USB-C / ワイヤレス',
    sourceUrl: 'https://news.samsung.com/jp/galaxy-s26-launch',
    checkedDate: '2026-05-08',
    strengths: ['167gで軽い', '256GB開始', 'Galaxy AIと7年更新'],
    cautions: ['Ultraほどのカメラ性能ではない', '販路でカラーや価格が変わりやすい'],
    bestFor: '軽いAndroid旗艦機を選びたい人',
  },
  {
    id: 'galaxy-s26-plus-256',
    name: 'Galaxy S26+',
    maker: 'Samsung',
    os: 'Android',
    generation: 'Galaxy S26',
    releaseYear: 2026,
    storageGb: 256,
    priceYen: 169920,
    priceNote: 'Samsungオンラインショップ 256GB',
    displayInch: 6.7,
    refreshRateHz: 120,
    weightG: 190,
    batteryLabel: '4,900mAh',
    batteryScore: 90,
    chip: 'Snapdragon / Exynos世代',
    ramGb: 12,
    mainCameraMp: 50,
    ultrawideMp: 12,
    telephotoMp: 10,
    opticalZoomLabel: '望遠搭載',
    cameraScore: 86,
    performanceScore: 91,
    aiScore: 92,
    videoScore: 86,
    updateYears: 7,
    waterResistance: 'IP68',
    charging: 'USB-C / ワイヤレス',
    sourceUrl: 'https://news.samsung.com/jp/galaxy-s26-launch',
    checkedDate: '2026-05-08',
    strengths: ['大画面とバッテリーのバランスが良い', '190gで大画面としては扱いやすい', '256GB開始'],
    cautions: ['片手操作はしにくい', 'カメラ最優先ならUltraが有利'],
    bestFor: '動画視聴、ゲーム、SNSを大画面で使いたい人',
  },
  {
    id: 'galaxy-s26-ultra-256',
    name: 'Galaxy S26 Ultra',
    maker: 'Samsung',
    os: 'Android',
    generation: 'Galaxy S26 Ultra',
    releaseYear: 2026,
    storageGb: 256,
    priceYen: 218900,
    priceNote: 'Samsungオンラインショップ 256GB',
    displayInch: 6.9,
    refreshRateHz: 120,
    weightG: 214,
    batteryLabel: '5,000mAh',
    batteryScore: 92,
    chip: 'Snapdragon世代',
    ramGb: 12,
    mainCameraMp: 200,
    ultrawideMp: 50,
    telephotoMp: 50,
    opticalZoomLabel: '高倍率望遠',
    cameraScore: 98,
    performanceScore: 96,
    aiScore: 96,
    videoScore: 94,
    updateYears: 7,
    waterResistance: 'IP68',
    charging: 'USB-C / ワイヤレス',
    sourceUrl: 'https://www.samsung.com/jp/smartphones/galaxy-s26-ultra/',
    checkedDate: '2026-05-08',
    strengths: ['カメラと大画面が最上位', 'Sシリーズ最大級の電池容量', 'AI機能と長期アップデート'],
    cautions: ['価格が高い', '214gで片手運用には重い'],
    bestFor: 'Androidでカメラ、大画面、性能を全部取りたい人',
  },
  {
    id: 'iphone-air-256',
    name: 'iPhone Air',
    maker: 'Apple',
    os: 'iOS',
    generation: 'iPhone Air',
    releaseYear: 2025,
    storageGb: 256,
    priceYen: 159800,
    priceNote: 'Apple直販 256GB',
    displayInch: 6.5,
    refreshRateHz: 120,
    weightG: 165,
    batteryLabel: 'ビデオ再生 最大27時間',
    batteryScore: 78,
    chip: 'A19 Pro',
    mainCameraMp: 48,
    opticalZoomLabel: '2倍相当',
    cameraScore: 76,
    performanceScore: 94,
    aiScore: 88,
    videoScore: 82,
    updateYears: 5,
    waterResistance: 'IP68',
    charging: 'USB-C / MagSafe',
    sourceUrl: 'https://www.apple.com/jp/shop/buy-iphone/iphone-air',
    checkedDate: '2026-05-08',
    strengths: ['薄型軽量で持ち歩きやすい', '大きめの120Hz画面', 'A19 Pro世代の性能'],
    cautions: ['単眼カメラ構成', '電池とカメラの総合力はProや標準17が有利'],
    bestFor: '軽さとデザインを最優先するiPhoneユーザー',
  },
  {
    id: 'iphone-17-pro-max-256',
    name: 'iPhone 17 Pro Max',
    maker: 'Apple',
    os: 'iOS',
    generation: 'iPhone 17 Pro',
    releaseYear: 2025,
    storageGb: 256,
    priceYen: 214800,
    priceNote: 'Apple直販 256GB目安',
    displayInch: 6.9,
    refreshRateHz: 120,
    weightG: 233,
    batteryLabel: 'ビデオ再生 最大39時間',
    batteryScore: 98,
    chip: 'A19 Pro',
    mainCameraMp: 48,
    ultrawideMp: 48,
    telephotoMp: 48,
    opticalZoomLabel: '最大8倍相当',
    cameraScore: 98,
    performanceScore: 97,
    aiScore: 91,
    videoScore: 99,
    updateYears: 5,
    waterResistance: 'IP68',
    charging: 'USB-C USB 3 / MagSafe 25W',
    sourceUrl: 'https://www.apple.com/jp/iphone-17-pro/specs/',
    checkedDate: '2026-05-08',
    strengths: ['iPhone最上位の電池持ち', '大画面で動画編集やゲームがしやすい', 'Pro動画機能が強い'],
    cautions: ['233gでかなり重い', '価格が高い'],
    bestFor: '大画面・電池・動画性能を最優先する人',
  },
  {
    id: 'pixel-10a-128',
    name: 'Google Pixel 10a',
    maker: 'Google',
    os: 'Android',
    generation: 'Pixel 10a',
    releaseYear: 2026,
    storageGb: 128,
    priceYen: 72800,
    priceNote: 'Googleストア価格目安',
    displayInch: 6.3,
    refreshRateHz: 120,
    weightG: 186,
    batteryLabel: '5,100mAh級',
    batteryScore: 88,
    chip: 'Google Tensor G4',
    ramGb: 8,
    mainCameraMp: 48,
    ultrawideMp: 13,
    opticalZoomLabel: 'デジタルズーム',
    cameraScore: 78,
    performanceScore: 78,
    aiScore: 88,
    videoScore: 76,
    updateYears: 7,
    waterResistance: 'IP67相当',
    charging: 'USB-C',
    sourceUrl: 'https://store.google.com/jp/product/pixel_10a?hl=ja',
    checkedDate: '2026-05-08',
    strengths: ['PixelのAI機能を安く使える', '長期アップデート', '電池持ち重視'],
    cautions: ['望遠なし', '上位Pixelより処理性能は控えめ'],
    bestFor: '安く長く使えるPixelが欲しい人',
  },
  {
    id: 'pixel-10-pro-xl-256',
    name: 'Google Pixel 10 Pro XL',
    maker: 'Google',
    os: 'Android',
    generation: 'Pixel 10 Pro',
    releaseYear: 2025,
    storageGb: 256,
    priceYen: 223960,
    priceNote: '国内キャリア本体価格目安',
    displayInch: 6.8,
    refreshRateHz: 120,
    weightG: 221,
    batteryLabel: 'Pro XL大容量',
    batteryScore: 94,
    chip: 'Google Tensor G5',
    ramGb: 16,
    mainCameraMp: 50,
    ultrawideMp: 48,
    telephotoMp: 48,
    opticalZoomLabel: '100倍ズーム',
    cameraScore: 97,
    performanceScore: 89,
    aiScore: 99,
    videoScore: 93,
    updateYears: 7,
    waterResistance: 'IP68',
    charging: 'USB-C / Pixelsnap Qi2',
    sourceUrl: 'https://store.google.com/jp/product/pixel_10_pro?hl=ja',
    checkedDate: '2026-05-08',
    strengths: ['Pixel最高クラスのAIとカメラ', '大画面', '7年アップデート'],
    cautions: ['重め', '価格が高い'],
    bestFor: 'Pixelで大画面と最高カメラを選びたい人',
  },
  {
    id: 'pixel-10-pro-fold-256',
    name: 'Google Pixel 10 Pro Fold',
    maker: 'Google',
    os: 'Android',
    generation: 'Pixel 10 Pro',
    releaseYear: 2025,
    storageGb: 256,
    priceYen: 302170,
    priceNote: '国内キャリア本体価格目安',
    displayInch: 8,
    refreshRateHz: 120,
    weightG: 258,
    batteryLabel: '5,015mAh級',
    batteryScore: 82,
    chip: 'Google Tensor G5',
    ramGb: 16,
    mainCameraMp: 48,
    ultrawideMp: 10.5,
    telephotoMp: 10.8,
    opticalZoomLabel: '望遠搭載',
    cameraScore: 86,
    performanceScore: 88,
    aiScore: 98,
    videoScore: 86,
    updateYears: 7,
    waterResistance: 'IP68',
    charging: 'USB-C / Pixelsnap Qi2',
    sourceUrl: 'https://store.google.com/jp/product/pixel_10_pro_fold?hl=ja',
    checkedDate: '2026-05-08',
    strengths: ['折りたたみ大画面', 'Pixel AIを大画面で使える', 'IP68対応'],
    cautions: ['非常に高価', '重さと厚みは通常スマホより不利'],
    bestFor: 'スマホと小型タブレットを1台にまとめたい人',
  },
  {
    id: 'xperia-1-vii-256',
    name: 'Xperia 1 VII',
    maker: 'Sony',
    os: 'Android',
    generation: 'Xperia VII',
    releaseYear: 2025,
    storageGb: 256,
    priceYen: 205000,
    priceNote: 'SIMフリー発売時目安',
    displayInch: 6.5,
    refreshRateHz: 120,
    weightG: 197,
    batteryLabel: '5,000mAh',
    batteryScore: 88,
    chip: 'Snapdragon 8 Elite',
    ramGb: 12,
    mainCameraMp: 48,
    ultrawideMp: 48,
    telephotoMp: 12,
    opticalZoomLabel: '可変望遠',
    cameraScore: 94,
    performanceScore: 94,
    aiScore: 82,
    videoScore: 92,
    updateYears: 4,
    waterResistance: 'IPX5/IPX8・IP6X',
    charging: 'USB-C / ワイヤレス',
    sourceUrl: 'https://www.sony.jp/xperia/products/xperia1m7/spec.html',
    checkedDate: '2026-05-08',
    strengths: ['カメラ/動画の手動操作が強い', 'microSD対応', 'ハイエンド性能'],
    cautions: ['価格が高い', '万人向けのAI補正はPixelやGalaxyが分かりやすい'],
    bestFor: 'カメラを自分で追い込みたい人',
  },
  {
    id: 'aquos-sense10-128',
    name: 'AQUOS sense10',
    maker: 'Sharp',
    os: 'Android',
    generation: 'AQUOS sense',
    releaseYear: 2026,
    storageGb: 128,
    priceYen: 62800,
    priceNote: '市場価格目安',
    displayInch: 6.1,
    refreshRateHz: 120,
    weightG: 166,
    batteryLabel: '5,000mAh',
    batteryScore: 90,
    chip: 'Snapdragon 7s Gen 3',
    ramGb: 6,
    mainCameraMp: 50,
    ultrawideMp: 50,
    opticalZoomLabel: 'デジタルズーム',
    cameraScore: 78,
    performanceScore: 74,
    aiScore: 74,
    videoScore: 72,
    updateYears: 5,
    waterResistance: 'IPX5/IPX8・IP6X',
    charging: 'USB-C PD 36W',
    sourceUrl: 'https://www.sharp.co.jp/k-tai/products/aquos-sense10/specs/',
    checkedDate: '2026-05-08',
    strengths: ['166gで軽い', '電池持ちが強い', 'microSDとおサイフ対応'],
    cautions: ['ゲーム性能はハイエンドに劣る', '望遠カメラなし'],
    bestFor: '軽くて長持ちする国内定番Androidが欲しい人',
  },
  {
    id: 'oppo-reno13-a-128',
    name: 'OPPO Reno13 A',
    maker: 'OPPO',
    os: 'Android',
    generation: 'Reno A',
    releaseYear: 2025,
    storageGb: 128,
    priceYen: 48800,
    priceNote: '市場価格目安',
    displayInch: 6.7,
    refreshRateHz: 120,
    weightG: 192,
    batteryLabel: '5,800mAh',
    batteryScore: 96,
    chip: 'Snapdragon 6 Gen 1',
    ramGb: 8,
    mainCameraMp: 50,
    ultrawideMp: 8,
    opticalZoomLabel: 'デジタルズーム',
    cameraScore: 74,
    performanceScore: 70,
    aiScore: 76,
    videoScore: 70,
    updateYears: 4,
    waterResistance: 'IP68/IP69相当',
    charging: '45W SUPERVOOC / PPS',
    sourceUrl: 'https://www.oppo.com/jp/smartphones/series-reno/reno13-a/',
    checkedDate: '2026-05-08',
    strengths: ['5,800mAhの大容量', '防水防塵が強い', '価格を抑えやすい'],
    cautions: ['処理性能はミドル級', '望遠なし'],
    bestFor: '電池持ち重視のミドルレンジが欲しい人',
  },
  {
    id: 'xiaomi-15-256',
    name: 'Xiaomi 15',
    maker: 'Xiaomi',
    os: 'Android',
    generation: 'Xiaomi 15',
    releaseYear: 2025,
    storageGb: 256,
    priceYen: 123000,
    priceNote: '市場価格目安',
    displayInch: 6.36,
    refreshRateHz: 120,
    weightG: 191,
    batteryLabel: '5,240mAh級',
    batteryScore: 88,
    chip: 'Snapdragon 8 Elite',
    ramGb: 12,
    mainCameraMp: 50,
    ultrawideMp: 50,
    telephotoMp: 50,
    opticalZoomLabel: '望遠搭載',
    cameraScore: 90,
    performanceScore: 96,
    aiScore: 86,
    videoScore: 88,
    updateYears: 5,
    waterResistance: 'IP68',
    charging: '90W級 / ワイヤレス',
    sourceUrl: 'https://www.mi.com/jp/mobile/',
    checkedDate: '2026-05-08',
    strengths: ['コンパクト寄りのハイエンド', 'Leica系カメラ', '高性能チップ'],
    cautions: ['価格は販路で変動', 'ソフトウェアの好みが分かれる'],
    bestFor: '小さめ高性能Androidが欲しい人',
  },
  {
    id: 'xiaomi-15-ultra-512',
    name: 'Xiaomi 15 Ultra',
    maker: 'Xiaomi',
    os: 'Android',
    generation: 'Xiaomi 15',
    releaseYear: 2025,
    storageGb: 512,
    priceYen: 179800,
    priceNote: '市場価格目安',
    displayInch: 6.73,
    refreshRateHz: 120,
    weightG: 226,
    batteryLabel: '5,410mAh級',
    batteryScore: 90,
    chip: 'Snapdragon 8 Elite',
    ramGb: 16,
    mainCameraMp: 50,
    ultrawideMp: 50,
    telephotoMp: 50,
    opticalZoomLabel: '高倍率望遠',
    cameraScore: 99,
    performanceScore: 97,
    aiScore: 88,
    videoScore: 96,
    updateYears: 5,
    waterResistance: 'IP68',
    charging: '90W級 / ワイヤレス',
    sourceUrl: 'https://www.mi.com/jp/mobile/',
    checkedDate: '2026-05-08',
    strengths: ['カメラ特化の最上位', '大容量ストレージ', '高性能'],
    cautions: ['重い', '価格が高い'],
    bestFor: 'スマホカメラを最優先する人',
  },
  {
    id: 'xiaomi-15t-pro-256',
    name: 'Xiaomi 15T Pro',
    maker: 'Xiaomi',
    os: 'Android',
    generation: 'Xiaomi 15T',
    releaseYear: 2025,
    storageGb: 256,
    priceYen: 109800,
    priceNote: '市場価格目安',
    displayInch: 6.83,
    refreshRateHz: 144,
    weightG: 210,
    batteryLabel: '5,500mAh級',
    batteryScore: 92,
    chip: 'Dimensity 9400+級',
    ramGb: 12,
    mainCameraMp: 50,
    ultrawideMp: 12,
    telephotoMp: 50,
    opticalZoomLabel: 'ペリスコープ望遠',
    cameraScore: 91,
    performanceScore: 94,
    aiScore: 84,
    videoScore: 88,
    updateYears: 5,
    waterResistance: 'IP68',
    charging: '90W級',
    sourceUrl: 'https://www.mi.com/jp/mobile/',
    checkedDate: '2026-05-08',
    strengths: ['価格対性能が高い', '望遠あり', '大画面144Hz'],
    cautions: ['大きく重め', 'ワイヤレス充電は要確認'],
    bestFor: '10万円前後で高性能とカメラを両立したい人',
  },
  {
    id: 'redmi-note-15-pro-256',
    name: 'REDMI Note 15 Pro 5G',
    maker: 'Xiaomi',
    os: 'Android',
    generation: 'REDMI Note 15',
    releaseYear: 2026,
    storageGb: 256,
    priceYen: 54980,
    priceNote: '市場想定価格 8GB/256GB',
    displayInch: 6.88,
    refreshRateHz: 120,
    weightG: 210,
    batteryLabel: '大容量バッテリー',
    batteryScore: 94,
    chip: 'Dimensity 7400-Ultra',
    ramGb: 8,
    mainCameraMp: 200,
    ultrawideMp: 8,
    opticalZoomLabel: 'デジタルズーム',
    cameraScore: 82,
    performanceScore: 76,
    aiScore: 74,
    videoScore: 74,
    updateYears: 4,
    waterResistance: 'IP66/IP68級',
    charging: '急速充電',
    sourceUrl: 'https://prtimes.jp/main/html/rd/p/000000204.000098799.html',
    checkedDate: '2026-05-08',
    strengths: ['5万円台で高画素カメラ', '大画面', '耐久性重視'],
    cautions: ['本格望遠なし', 'サイズは大きい'],
    bestFor: '5万円台で大画面と電池を重視する人',
  },
  {
    id: 'poco-f8-pro-256',
    name: 'POCO F8 Pro',
    maker: 'Xiaomi',
    os: 'Android',
    generation: 'POCO F',
    releaseYear: 2026,
    storageGb: 256,
    priceYen: 89980,
    priceNote: '市場想定価格 12GB/256GB',
    displayInch: 6.67,
    refreshRateHz: 120,
    weightG: 210,
    batteryLabel: '大容量',
    batteryScore: 86,
    chip: 'Snapdragon 8 Elite',
    ramGb: 12,
    mainCameraMp: 50,
    ultrawideMp: 8,
    telephotoMp: 50,
    opticalZoomLabel: '望遠搭載',
    cameraScore: 84,
    performanceScore: 96,
    aiScore: 84,
    videoScore: 84,
    updateYears: 4,
    waterResistance: '要確認',
    charging: '急速充電',
    sourceUrl: 'https://news.mynavi.jp/article/20260122-4017434/',
    checkedDate: '2026-05-08',
    strengths: ['10万円未満で最上位級チップ', 'ゲーム性能が高い', '12GB RAM'],
    cautions: ['販路とセールで価格差が大きい', 'カメラ重視ならUltra系も検討'],
    bestFor: 'ゲーム性能とコスパを重視する人',
  },
  {
    id: 'motorola-edge-60-pro-256',
    name: 'motorola edge 60 pro',
    maker: 'motorola',
    os: 'Android',
    generation: 'edge 60',
    releaseYear: 2026,
    storageGb: 256,
    priceYen: 84800,
    priceNote: 'モトローラ公式オンラインストア',
    displayInch: 6.7,
    refreshRateHz: 120,
    weightG: 184,
    batteryLabel: '5,000mAh',
    batteryScore: 90,
    chip: 'Dimensity 8350',
    ramGb: 12,
    mainCameraMp: 50,
    ultrawideMp: 50,
    telephotoMp: 10,
    opticalZoomLabel: '3倍光学望遠',
    cameraScore: 88,
    performanceScore: 84,
    aiScore: 82,
    videoScore: 84,
    updateYears: 4,
    waterResistance: 'IP68/IP69・MIL',
    charging: '125W / 15Wワイヤレス',
    sourceUrl: 'https://store.motorola.co.jp/item/EDGE60PRO.html',
    checkedDate: '2026-05-08',
    strengths: ['3倍望遠あり', '184gで大画面として軽い', '125W充電'],
    cautions: ['OS更新方針は購入前確認推奨', 'カーブ画面の好みが分かれる'],
    bestFor: '8万円台で望遠・急速充電・軽さを狙う人',
  },
  {
    id: 'zenfone-12-ultra-256',
    name: 'Zenfone 12 Ultra',
    maker: 'ASUS',
    os: 'Android',
    generation: 'Zenfone 12',
    releaseYear: 2025,
    storageGb: 256,
    priceYen: 149800,
    priceNote: 'ASUS Store通常価格 12GB/256GB',
    displayInch: 6.78,
    refreshRateHz: 144,
    weightG: 220,
    batteryLabel: '5,500mAh級',
    batteryScore: 90,
    chip: 'Snapdragon 8 Elite',
    ramGb: 12,
    mainCameraMp: 50,
    ultrawideMp: 13,
    telephotoMp: 32,
    opticalZoomLabel: '3倍光学望遠',
    cameraScore: 90,
    performanceScore: 96,
    aiScore: 86,
    videoScore: 90,
    updateYears: 4,
    waterResistance: 'IP65/IP68',
    charging: 'USB-C / ワイヤレス',
    sourceUrl: 'https://store.asus.com/jp/zenfone-12-ultra.html',
    checkedDate: '2026-05-08',
    strengths: ['ジンバルOIS', '高性能チップ', 'ゲーミング寄りの144Hz'],
    cautions: ['220gで重め', '在庫やセール価格が変わりやすい'],
    bestFor: '動画の手ブレ補正と高性能を重視する人',
  },
  {
    id: 'nothing-phone-3a-128',
    name: 'Nothing Phone (3a)',
    maker: 'Nothing',
    os: 'Android',
    generation: 'Phone (3a)',
    releaseYear: 2025,
    storageGb: 128,
    priceYen: 54800,
    priceNote: '日本発売時価格 8GB/128GB',
    displayInch: 6.77,
    refreshRateHz: 120,
    weightG: 201,
    batteryLabel: '5,000mAh',
    batteryScore: 84,
    chip: 'Snapdragon 7s Gen 3',
    ramGb: 8,
    mainCameraMp: 50,
    ultrawideMp: 8,
    telephotoMp: 50,
    opticalZoomLabel: '望遠搭載',
    cameraScore: 82,
    performanceScore: 76,
    aiScore: 74,
    videoScore: 76,
    updateYears: 6,
    waterResistance: 'IP64級',
    charging: 'USB-C',
    sourceUrl: 'https://news.mynavi.jp/article/20250408-3177745/',
    checkedDate: '2026-05-08',
    strengths: ['5万円台で望遠とFeliCa', 'デザインが個性的', '大画面OLED'],
    cautions: ['ハイエンド性能ではない', '防水等級は上位機ほど強くない'],
    bestFor: 'デザインとコスパを両立したい人',
  },
  {
    id: 'nubia-z70s-ultra-512',
    name: 'nubia Z70S Ultra',
    maker: 'nubia',
    os: 'Android',
    generation: 'Z70S Ultra',
    releaseYear: 2025,
    storageGb: 512,
    priceYen: 129800,
    priceNote: 'nubia Store JP 16GB/512GB',
    displayInch: 6.85,
    refreshRateHz: 144,
    weightG: 228,
    batteryLabel: '6,600mAh',
    batteryScore: 98,
    chip: 'Snapdragon 8 Elite',
    ramGb: 16,
    mainCameraMp: 50,
    ultrawideMp: 50,
    telephotoMp: 64,
    opticalZoomLabel: '70mm望遠',
    cameraScore: 94,
    performanceScore: 96,
    aiScore: 82,
    videoScore: 90,
    updateYears: 3,
    waterResistance: 'IP68/IP69',
    charging: '最大80W',
    sourceUrl: 'https://jp.nubia.com/products/nubia-z70s-ultra',
    checkedDate: '2026-05-08',
    strengths: ['6,600mAhの大容量', '画面下カメラで没入感が高い', '16GB/512GBで価格が強い'],
    cautions: ['228gで重い', '在庫状況に注意'],
    bestFor: 'ゲーム・大画面・電池を重視する人',
  },
  {
    id: 'oppo-find-x8-256',
    name: 'OPPO Find X8',
    maker: 'OPPO',
    os: 'Android',
    generation: 'Find X',
    releaseYear: 2024,
    storageGb: 256,
    priceYen: 139800,
    priceNote: '発売時価格目安',
    displayInch: 6.59,
    refreshRateHz: 120,
    weightG: 193,
    batteryLabel: '5,630mAh級',
    batteryScore: 92,
    chip: 'Dimensity 9400',
    ramGb: 16,
    mainCameraMp: 50,
    ultrawideMp: 50,
    telephotoMp: 50,
    opticalZoomLabel: '望遠搭載',
    cameraScore: 92,
    performanceScore: 95,
    aiScore: 86,
    videoScore: 90,
    updateYears: 5,
    waterResistance: 'IP68/IP69',
    charging: '急速充電',
    sourceUrl: 'https://www.oppo.com/jp/smartphones/series-find-x/find-x8/',
    checkedDate: '2026-05-08',
    strengths: ['カメラと性能のバランスが高い', '大容量バッテリー', '比較的軽め'],
    cautions: ['販路で在庫と価格が変わりやすい', '望遠倍率はUltra級ほどではない'],
    bestFor: 'OPPOの高性能カメラ機を狙う人',
  },
  {
    id: 'oppo-reno14-256',
    name: 'OPPO Reno14 5G',
    maker: 'OPPO',
    os: 'Android',
    generation: 'Reno',
    releaseYear: 2026,
    storageGb: 256,
    priceYen: 79800,
    priceNote: '市場価格目安',
    displayInch: 6.59,
    refreshRateHz: 120,
    weightG: 187,
    batteryLabel: '大容量',
    batteryScore: 90,
    chip: 'Dimensity 8350級',
    ramGb: 12,
    mainCameraMp: 50,
    ultrawideMp: 8,
    telephotoMp: 50,
    opticalZoomLabel: '望遠搭載',
    cameraScore: 86,
    performanceScore: 82,
    aiScore: 80,
    videoScore: 82,
    updateYears: 4,
    waterResistance: 'IP68/IP69級',
    charging: '急速充電',
    sourceUrl: 'https://www.oppo.com/jp/smartphones/',
    checkedDate: '2026-05-08',
    strengths: ['ミドル上位で望遠あり', 'AI写真編集', '軽めの本体'],
    cautions: ['価格と仕様は販路で確認推奨', 'ゲーム最優先なら上位チップ機が有利'],
    bestFor: '8万円前後で写真と普段使いを重視する人',
  },
  {
    id: 'oppo-a5-5g-128',
    name: 'OPPO A5 5G',
    maker: 'OPPO',
    os: 'Android',
    generation: 'A',
    releaseYear: 2026,
    storageGb: 128,
    priceYen: 32800,
    priceNote: '市場価格目安',
    displayInch: 6.67,
    refreshRateHz: 120,
    weightG: 194,
    batteryLabel: '大容量',
    batteryScore: 90,
    chip: 'エントリー5G SoC',
    ramGb: 4,
    mainCameraMp: 50,
    opticalZoomLabel: 'デジタルズーム',
    cameraScore: 62,
    performanceScore: 58,
    aiScore: 58,
    videoScore: 58,
    updateYears: 3,
    waterResistance: '生活防水級',
    charging: 'USB-C',
    sourceUrl: 'https://www.oppo.com/jp/smartphones/',
    checkedDate: '2026-05-08',
    strengths: ['価格が安い', '大画面', '日常用途向け'],
    cautions: ['重いゲームや高画質動画編集には不向き', 'カメラは記録用途中心'],
    bestFor: '安く5Gスマホを持ちたい人',
  },
  {
    id: 'aquos-r10-256',
    name: 'AQUOS R10',
    maker: 'Sharp',
    os: 'Android',
    generation: 'AQUOS R',
    releaseYear: 2025,
    storageGb: 256,
    priceYen: 99900,
    priceNote: '市場価格目安',
    displayInch: 6.5,
    refreshRateHz: 240,
    weightG: 197,
    batteryLabel: '5,000mAh級',
    batteryScore: 86,
    chip: 'Snapdragon 7+ Gen 3級',
    ramGb: 12,
    mainCameraMp: 50,
    ultrawideMp: 50,
    opticalZoomLabel: 'デジタルズーム',
    cameraScore: 86,
    performanceScore: 84,
    aiScore: 78,
    videoScore: 84,
    updateYears: 5,
    waterResistance: 'IPX5/IPX8・IP6X',
    charging: 'USB-C',
    sourceUrl: 'https://www.sharp.co.jp/k-tai/products/',
    checkedDate: '2026-05-08',
    strengths: ['AQUOS上位の画面とカメラ', '国内機能が充実', '長期利用向け'],
    cautions: ['望遠カメラなし', '価格は販路差が大きい'],
    bestFor: '国内機能込みの上位AQUOSが欲しい人',
  },
  {
    id: 'aquos-wish5-64',
    name: 'AQUOS wish5',
    maker: 'Sharp',
    os: 'Android',
    generation: 'AQUOS wish',
    releaseYear: 2025,
    storageGb: 64,
    priceYen: 38800,
    priceNote: '市場価格目安',
    displayInch: 6.6,
    refreshRateHz: 90,
    weightG: 187,
    batteryLabel: '5,000mAh級',
    batteryScore: 86,
    chip: 'エントリー5G SoC',
    ramGb: 4,
    mainCameraMp: 50,
    opticalZoomLabel: 'デジタルズーム',
    cameraScore: 60,
    performanceScore: 56,
    aiScore: 54,
    videoScore: 54,
    updateYears: 5,
    waterResistance: 'IPX5/IPX8・IP6X',
    charging: 'USB-C',
    sourceUrl: 'https://www.sharp.co.jp/k-tai/products/',
    checkedDate: '2026-05-08',
    strengths: ['安い', '国内機能と耐久性', '長く使いやすい'],
    cautions: ['容量64GBは不足しやすい', '性能は控えめ'],
    bestFor: '通話・連絡・決済中心の安価な国内スマホが欲しい人',
  },
  {
    id: 'moto-g66j-128',
    name: 'moto g66j 5G',
    maker: 'motorola',
    os: 'Android',
    generation: 'moto g',
    releaseYear: 2025,
    storageGb: 128,
    priceYen: 34800,
    priceNote: '市場価格目安',
    displayInch: 6.7,
    refreshRateHz: 120,
    weightG: 200,
    batteryLabel: '5,200mAh級',
    batteryScore: 88,
    chip: 'Dimensity 7060級',
    ramGb: 8,
    mainCameraMp: 50,
    ultrawideMp: 8,
    opticalZoomLabel: 'デジタルズーム',
    cameraScore: 66,
    performanceScore: 66,
    aiScore: 60,
    videoScore: 62,
    updateYears: 3,
    waterResistance: 'IP68/IP69級',
    charging: 'USB-C',
    sourceUrl: 'https://store.motorola.co.jp/item/MOTO_G66J_5G.html',
    checkedDate: '2026-05-08',
    strengths: ['3万円台で大画面', '電池持ち', '防水防塵が強め'],
    cautions: ['重め', 'カメラと処理性能は価格相応'],
    bestFor: '安価で大画面のAndroidが欲しい人',
  },
  {
    id: 'xiaomi-15t-256',
    name: 'Xiaomi 15T',
    maker: 'Xiaomi',
    os: 'Android',
    generation: 'Xiaomi 15T',
    releaseYear: 2025,
    storageGb: 256,
    priceYen: 74800,
    priceNote: '市場価格目安',
    displayInch: 6.83,
    refreshRateHz: 120,
    weightG: 194,
    batteryLabel: '5,500mAh級',
    batteryScore: 92,
    chip: 'Dimensity 8400級',
    ramGb: 12,
    mainCameraMp: 50,
    ultrawideMp: 12,
    telephotoMp: 50,
    opticalZoomLabel: '望遠搭載',
    cameraScore: 86,
    performanceScore: 84,
    aiScore: 80,
    videoScore: 82,
    updateYears: 5,
    waterResistance: 'IP68',
    charging: '急速充電',
    sourceUrl: 'https://www.mi.com/jp/mobile/',
    checkedDate: '2026-05-08',
    strengths: ['15T Proより安い', '大画面と電池', '望遠あり'],
    cautions: ['Proより処理性能は控えめ', '大きめ'],
    bestFor: '7万円台で大画面・電池・カメラを重視する人',
  },
  {
    id: 'redmi-15-5g-128',
    name: 'REDMI 15 5G',
    maker: 'Xiaomi',
    os: 'Android',
    generation: 'REDMI',
    releaseYear: 2026,
    storageGb: 128,
    priceYen: 29800,
    priceNote: '市場価格目安',
    displayInch: 6.9,
    refreshRateHz: 120,
    weightG: 215,
    batteryLabel: '7,000mAh',
    batteryScore: 99,
    chip: 'エントリー5G SoC',
    ramGb: 4,
    mainCameraMp: 50,
    opticalZoomLabel: 'デジタルズーム',
    cameraScore: 58,
    performanceScore: 56,
    aiScore: 54,
    videoScore: 54,
    updateYears: 3,
    waterResistance: '生活防水級',
    charging: 'USB-C',
    sourceUrl: 'https://www.mi.com/jp/mobile/',
    checkedDate: '2026-05-08',
    strengths: ['7,000mAh級の電池', '安い', '大画面'],
    cautions: ['重い', '性能とカメラはエントリー級'],
    bestFor: '電池持ち最優先のサブ機・家族用',
  },
]
